<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="6" hostname="blackberry" failures="4" tests="17" name="Test" time="20.231" errors="0" timestamp="2025-08-13T23:55:32 IST">
  <testcase classname="passenger.AddPassengerTest" name="testAddPassenger" time="0.954"/>
  <testcase classname="passenger.AddPassengerTest" name="testAddPassenger" time="0.599">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Expected 409 Conflict for duplicate ID expected [409] but found [200],
	List changed unexpectedly on duplicate ID expected [1] but found [2]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Expected 409 Conflict for duplicate ID expected [409] but found [200],
List changed unexpectedly on duplicate ID expected [1] but found [2]
at passenger.AddPassengerTest.testAddPassenger(AddPassengerTest.java:85)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- testAddPassenger -->
  <testcase classname="passenger.AddPassengerTest" name="testAddPassenger" time="0.714">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Expected 400 Bad Request for empty fields expected [400] but found [200],
	Invalid passenger should not be added to list expected [0] but found [1]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Expected 400 Bad Request for empty fields expected [400] but found [200],
Invalid passenger should not be added to list expected [0] but found [1]
at passenger.AddPassengerTest.testAddPassenger(AddPassengerTest.java:70)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- testAddPassenger -->
  <testcase classname="passenger.ViewPassengerByNameAndMobile" name="testViewPassengerByNameMobile" time="0.603"/>
  <testcase classname="passenger.ViewPassengerByNameAndMobile" name="testViewPassengerByNameMobile" time="0.82"/>
  <testcase classname="passenger.ViewPassengerByNameAndMobile" name="testViewPassengerByNameMobile" time="0.611"/>
  <testcase classname="passenger.ViewPassengerByNameAndMobile" name="testViewPassengerByNameMobile" time="0.719"/>
  <testcase classname="passenger.ViewPassengerByIdTest" name="testViewPassengerById" time="1.423"/>
  <testcase classname="passenger.ViewPassengerByIdTest" name="testViewPassengerById" time="0.63"/>
  <testcase classname="passenger.ViewPassengerByIdTest" name="testViewPassengerById" time="0.628"/>
  <testcase classname="passenger.ViewPassengerByIdTest" name="testViewPassengerById" time="0.715"/>
  <testcase classname="passenger.ViewPassengerList" name="testViewPassengerList" time="1.753"/>
  <testcase classname="passenger.DeletePassengerById" name="testDeletePassengerById" time="1.75"/>
  <testcase classname="passenger.DeletePassengerById" name="testDeletePassengerById" time="0.722"/>
  <testcase classname="passenger.DeletePassengerById" name="testDeletePassengerById" time="0.59">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Unexpected success for non-existent passenger">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Unexpected success for non-existent passenger
at passenger.DeletePassengerById.testDeletePassengerById(DeletePassengerById.java:83)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- testDeletePassengerById -->
  <testcase classname="passenger.DeletePassengerById" name="testDeletePassengerById" time="0.611">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Unexpected success for non-existent passenger">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Unexpected success for non-existent passenger
at passenger.DeletePassengerById.testDeletePassengerById(DeletePassengerById.java:83)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- testDeletePassengerById -->
  <testcase classname="auth.AuthTest" name="testAuthCode" time="0.641"/>
  <testcase classname="base.BaseTest" name="@BeforeSuite setExtentReport" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite setExtentReport -->
  <testcase classname="base.BaseTest" name="@BeforeSuite setExtentReport" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite setExtentReport -->
  <testcase classname="base.BaseTest" name="@BeforeSuite setExtentReport" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite setExtentReport -->
  <testcase classname="base.BaseTest" name="@BeforeSuite setExtentReport" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite setExtentReport -->
  <testcase classname="base.BaseTest" name="@BeforeSuite setExtentReport" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite setExtentReport -->
  <testcase classname="base.BaseTest" name="@BeforeSuite setExtentReport" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite setExtentReport -->
</testsuite> <!-- Test -->
